build_image:
  only:
    - feature/config_CI_CD
  script:
    - echo "build jar file"
    - touch hello.txt
#    - docker build -t khuvid19/coreapi .
#    - docker run --rm khuvid19/coreapi
  tags:
    - KHUVID_19