build_image:
  only:
    - feature/config_CI_CD
  script:
    - echo "...BUILD DOCKERFILE... PLZ RUN WELL"
    - docker build -t khuvid .
    - docker images list
    - docker run -d -p 8080:8080 khuvid
  tags:
    - KHUVID_19