image: gradle:alpine
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/

build_image:
  only:
    - feature/config_CI_CD
    - develop
  script:
    - ./gradlew clean
    - ./gradlew build
    - docker container stop api
    - docker container rm api
    - docker image rm khuvid19/coreapi
    - docker build -t khuvid19/coreapi .
    - docker run -d -it -p 20505:8080 --name api khuvid19/coreapi
  tags:
    - KHUVID_19