build_image:
  only:
    - feature/config_CI_CD
  script:
    - echo "build jar file"
    - - echo "build jar wahat"
    - docker build -t khuvid19/coreapi .
    - docker run -d -p 8080:8080 khuvid19/coreapi
  tags:
    - KHUVID_19